debug_mode: True
use_log: True
robot_id: 0

role_info:
    is_client: True
    id: 'vehicle-01'

network_info:
    ip: '127.0.0.1'

    target_info:
        ip: '10.12.120.84'

message_info:
    # msg:
    #     is_tcp: True
    #     port: 11000
    # odm:
    #     is_tcp: True
    #     port: 12000
    # pcd:
    #     is_tcp: True
    #     port: 13000
    # cmd:
    #     is_tcp: True
    #     port: 14000
    # img:
    #     is_tcp: True
    #     width: 640
    #     height: 480
    #     port: 15000
    pcd_kf:
        is_tcp: True
        port: 16000