debug_mode: False
use_log: False
robot_id: 0

role_info:
    #send so this is a client
    is_client: True
    id: 'vehicle-02'

network_info:
    ip: '127.0.0.1'

    target_info:
        ip: '10.181.213.247'

message_info:
    msg:
        is_tcp: True
        port: 11000
    odm:
        is_tcp: True
        port: 12000
    pcd:
        is_tcp: True
        port: 13000
    cmd:
        is_tcp: True
        port: 14000
    img:
        is_tcp: True
        port: 15000
