debug_mode: True
use_log: False
robot_id: 0

role_info:
    is_client: False
    id: 'vehicle-02'

network_info:
    ip: '127.0.0.1'

    target_info:
        ip: '127.0.0.1'

message_info:
    msg:
        is_tcp: True
        port: 11000
    odm:
        is_tcp: True
        port: 12000
    pcd:
        is_tcp: True
        port: 13000
    cmd:
        is_tcp: True
        port: 14000
    img:
        is_tcp: True
        width: 640
        height: 480
        port: 15000
